# Generated by Django 3.1.4 on 2021-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=10)),
                ('Nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(max_length=10)),
                ('countrydesc', models.CharField(max_length=10)),
            ],
        ),
    ]
