# Generated by Django 3.1.4 on 2021-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencecode', models.CharField(max_length=10)),
                ('residencedesc', models.CharField(max_length=10)),
            ],
        ),
    ]
